---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mysql
  namespace: default
  labels:
    app: wordpress
type: Opaque
data:
  mysql-admin-user: "YWRtaW4="         # base64 encoded admin username - admin
  mysql-admin-password: "cGFzc3dvcmQ=" # base64 encoded password   - password
  mysql-root-password: "cGFzc3dvcmQ="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
data:
  mysqld.cnf: |
    [mysqld]
    pid-file = /var/run/mysqld/mysqld.pid
    #socket = /var/run/mysqld/mysqld.sock
    datadir = /var/lib/mysql
    bind-address = 0.0.0.0
    symbolic-links=0