apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-storageos
  labels:
    app: prometheus-operator
spec:
  #serviceMonitorSelector: {} This probably makes it monitor all
  #serviceMonitors
  resources:
    requests:
      memory: 400Mi
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
