apiVersion: v1
kind: Service
metadata:
  name: prometheus-storagoes
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-storageos
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    prometheus: prometheus-storageos
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
