kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: nfs
  namespace: storageos
spec:
  serviceName: "nfs"
  replicas: 1 # Only one is permitted to register as a provisioner
  template:
    metadata:
      labels:
        app: nfs
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      serviceAccount: nfs-provisioner
      terminationGracePeriodSeconds: 0
      containers:
        - name: nfs-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner:v1.0.9
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=storageos/nfs"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: nfs
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: persistent-volume
              mountPath: /export
      #volumes:
        #- name: export-volume
          #persistentVolumeClaim:
            #claimName: fast-pvc1
  volumeClaimTemplates:
    -
      metadata:
        name: "persistent-volume"
      spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "fast"
          resources:
              requests:
                  storage: 10Gi
