apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageos
  labels:
    app: storageos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: storageos
  labels:
    app: storageos
rules:
  - apiGroups:
    - ""
    resources:
      - secrets
    verbs:
      - create
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storageos
  labels:
    app: storageos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: storageos
subjects:
  - kind: ServiceAccount
    name: storageos
---
apiVersion: v1
kind: Service
metadata:
  name: storageos
  namespace: default
  labels:
    app: storageos
spec:
  type: ClusterIP
  ports:
    - port: 5705
      targetPort: 5705
      protocol: TCP
      name: storageos
  selector:
    app: storageos
