apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
        name: pause
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: storageos
                operator: In
                values:
                - compute-only
      containers:
      - name: test
        image: k8s.gcr.io/pause:2.0
