# Create a pod with three containers:
# main -
# rsyncd - listening on port 873
# nginx - listening on port 80
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backup-example
spec:
  selector:
    matchLabels:
      app: backup-example
  serviceName: "backup-example"
  replicas: 1
  template:
    metadata:
      labels:
        app: backup-example
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: main
        image: debian:9-slim
        command: ["/bin/sleep"]
        args: ["infinity"]
        volumeMounts:
        - name: data
          mountPath: /data
      - name: rsyncd
        image: vimagick/rsyncd
        volumeMounts:
        - name: data
          mountPath: /share
        - name: rsync-config
          mountPath: /etc/rsyncd.conf
          subPath: rsyncd.conf
        - name: rsync-secrets
          mountPath: /etc/rsyncd.secrets
          subPath: rsyncd.secrets
        ports:
        -  containerPort: 873
      - name: nginx
        image: nginx
        ports:
        -  containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      - name: sftp
        image: atmoz/sftp:latest
        ports:
        - containerPort: 22
        volumeMounts:
        - name: data
          mountPath: /home/alex
        - name: sftp-config
          mountPath: /etc/sftp/users.conf
          subPath: users.conf 
        - name: ssh-key
          mountPath: /home/alex/.ssh/keys/id_rsa.pub
          subPath: id_rsa.pub
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: rsync-config
        configMap:
          name: rsync-config
      - name: rsync-secrets
        secret:
          secretName: rsync-credentials
          defaultMode: 0600
          items:
          - key: credentials
            path: rsyncd.secrets
      - name: sftp-config
        secret:
          secretName: sftp-config
          items:
          - key: users.conf
            path: users.conf
      - name: ssh-key
        configMap:
          name: ssh-key-pub
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        env: prod
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "fast"
      resources:
        requests:
          storage: 5Gi
