kind: Pod
apiVersion: v1
metadata:
  name: demo
spec:
#  nodeSelector:
#    kubernetes.io/hostname: node01
  containers:
  - name: pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "sleep 3600"
    volumeMounts:
      - name: storageos-vol
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: storageos-vol
      persistentVolumeClaim:
        claimName: pvc-1
