apiVersion: v1
kind: Secret
metadata:
  name: {{ secret_name }}
  namespace: {{ secret_namespace }}
  labels:
    app: storageos
type: "kubernetes.io/storageos"
data:
  apiAddress: "{{ hostvars[groups['storageos'][0]]['openshift_ip'] | regex_replace('(.*)', 'tcp://\\1:5705') | b64encode }}"
  apiUsername: "c3RvcmFnZW9z"
  apiPassword: "c3RvcmFnZW9z"
# {{ hostvars[groups['storageos'][0]]['openshift_ip'] | regex_replace('(.*)', 'tcp://\\1:5705') }}
# {{ hostvars[groups['storageos'][0]]['openshift_ip'] | map('regex_replace', '(.*)', 'tcp://\\1:5705') }}
# {{ groups['storageos'] | map('extract', hostvars, 'openshift_ip')| map('regex_replace', '(.*)', 'tcp://\\1:5705') | join(',') }}"
