apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
    - name: postgres-client
      image: crunchydata/crunchy-postgres:centos7-10.4-1.8.3
      command: ["/bin/sleep"]
      args: [ "3600" ]
