apiVersion: v1
kind: Pod
metadata:
  name: test2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: storageos
            operator: In
            values:
            - compute-only
  containers:
  - name: test
    image: k8s.gcr.io/pause:2.0
