---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  # namespace: elasticsearch
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      serviceAccountName: elasticsearch
      containers:
        - name: es-master
          image: elasticsearch:6.7.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: "es"
            - name: NUMBER_OF_MASTERS
              value: "3"
            - name: NODE_MASTER
              value: "true"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: NETWORK_HOST
              value: "_eth0:ipv4_"
            - name: DISCOVERY_SERVICE
              value: "es-discovery"
            - name: LICENSE
              value: "basic"
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          ports:
            - containerPort: 9300
              name: transport
          livenessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
            - name: log4j
              mountPath: /usr/share/elasticsearch/config/log4j2.properties
              subPath: log4j2.properties
          securityContext:
            privileged: false
      tolerations: []
      volumes:
        - name: data
          emptyDir: {}
        - name: log4j
          configMap:
            name: log4j
            items:
              - key: log4j.properties
                path: log4j2.properties
