---
# Source: zookeeper/templates/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    chart: zookeeper-1.2.2
    release: zookeeper
    heritage: Tiller
    component: server
spec:
  selector:
    matchLabels:
      app: zookeeper
      release: zookeeper
      component: server
  maxUnavailable: 1
