apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0002
  labels:
    "storageos.com/encryption": "true"
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
