apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-vol-1-test
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
