kind: Service
apiVersion: v1
metadata:
  name: nfs
  namespace: storageos
  labels:
    app: nfs
spec:
  type: NodePort
  ports:
    - name: nfs
      port: 2049
      nodePort: 32049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: nfs
