---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
    tier: frontend
type: Opaque
data:
  wordpress-db-password: "cGFzc3dvcmQ=" # base64 encoded password   - password