apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: test-ingress
  labels:
    app: wordpress
    tier: frontend
  annotations:
    kubernetes.io/ingress.class: "nginx" # not sure if this works on ovirt but works with rancher
    # Enable client certificate authentication
    #nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # Create the secret containing the trusted ca certificates
    #nginx.ingress.kubernetes.io/auth-tls-secret: "default/tls-certificate"
spec:
  tls:
    - hosts:
      - test.example.com
      secretName: tls-certificate 
  rules:
    - host: test.example.com
      http:
        paths:
        - path: /
          backend:
            serviceName: wordpress
            servicePort: 8080
