kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: v1-storageos-statefulset
  namespace: storageos
  labels:
    app: storageos
spec:
  serviceName: storageos
  replicas: 1
  selector:
    matchLabels:
      app: storageos
  template:
    metadata:
      labels:
        app: storageos
    spec:
      serviceAccount: v1-storageos-statefulset-sa
      containers:
      - name: csi-external-provisioner
        image: "quay.io/k8scsi/csi-provisioner:canary"
        imagePullPolicy: Always
        args:
          - "--v=5"
          - "--provisioner=storageos"
          - "--csi-address=$(ADDRESS)"
        env:
          - name: ADDRESS
            value: /csi/csi.sock # plugin-dir is mounted at /csi
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi
      - name: csi-external-attacher
        image: "quay.io/k8scsi/csi-attacher:canary"
        imagePullPolicy: Always
        args:
          - "--v=5"
          - "--csi-address=$(ADDRESS)"
        env:
          - name: ADDRESS
            value: /csi/csi.sock
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/storageos/
            type: DirectoryOrCreate
